lms/urls.py
from core.views import index

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', index, name="index"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import edit_student, generate_students, remove_student, students_create, view_all_students

app_name = 'students'

urlpatterns = [
    path('list/', view_all_students, name='list_all'),
    path('generate/', generate_students, name='generate'),
    path('create/', students_create, name='create'),
    path('edit/<str:student_id>', edit_student, name='edit'),
    path('remove/<str:student_id>', remove_student, name='remove')
]

students/models.py
import uuid as uuid

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField


class Student(models.Model):
    first_name = models.CharField(max_length=150, null=False)
    last_name = models.CharField(max_length=150, null=False)
    date_of_birth = models.DateField(null=True)
    rating = models.PositiveSmallIntegerField(null=True, default=0,
                                              validators=[MaxValueValidator(100), MinValueValidator(1)])
    phone_number = PhoneNumberField(null=True, region="UA")
    uuid = models.UUIDField(auto_created=True, editable=False, default=uuid.uuid4)

    group = models.ForeignKey(
        to='groups.Group',
        on_delete=models.SET_NULL,
        null=True,
        related_name='group_of_student'
    )

    def __str__(self):
        return f'{self.first_name}  {self.last_name}'

students/forms.py
from django import forms

from phonenumber_field.formfields import PhoneNumberField

from students.models import Student


class CreateStudentForm(forms.ModelForm):
    phone_number = PhoneNumberField(required=True, region="UA", widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter UA phone number',
    }))

    # date_of_birth = forms.DateField(widget=AdminDateWidget())

    class Meta:
        model = Student
        fields = ['last_name', 'first_name', 'rating', 'phone_number', 'date_of_birth', 'group']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'class': 'date_picker'})
        }

students/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from students import utils
from students.forms import CreateStudentForm
from students.models import Student


def generate_students(request):
    return HttpResponse(utils.generate_students(request))


def view_all_students(request):
    all_students = utils.get_all_students()
    if request.method == 'GET':
        params = [
            'first_name',
            'last_name',
            'rating',
        ]
        for param in params:
            value = request.GET.get(param)
            if value:
                all_students = all_students.filter(**{param: value})

    return render(
        request=request,
        context={
            'all_students': all_students,
        },
        template_name='view-all-students.html'
    )


def students_create(request):
    if request.method == 'GET':
        form = CreateStudentForm()

    elif request.method == "POST":
        form = CreateStudentForm(
            data=request.POST,
        )

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:list_all"))

    return render(
        request=request,
        context={
            "form": form
        },
        template_name="students-edit.html"

    )


def edit_student(request, student_id):
    try:
        student = Student.objects.get(uuid=student_id)
    except Student.DoesNotExist:
        return Http404("Student DoesNotExist")

    if request.method == "POST":
        form = CreateStudentForm(
            instance=student,
            data=request.POST
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:list_all"))

    else:
        form = CreateStudentForm(
            instance=student,
        )

    return render(
        request=request,
        context={
            "form": form,
        },
        template_name="students-edit.html",
    )


def remove_student(request, student_id):
    student = get_object_or_404(Student, uuid=student_id)
    if request.method == 'POST':
        student.delete()
        return redirect(reverse('students:list_all'))
    return render(
        request=request,
        context={
            "student": student,
            "what_to_delete": str(student)
        },
        template_name='student-delete.html',
    )

students/templates/student-delete.html
{% extends 'base.html' %}
{% block title %}
    <title>Delete student</title>
{% endblock %}
{% block content %}
    {% include 'include/delete_record.html' %}
{% endblock %}

students/templates/students-create.html
{% extends 'base.html' %}
{% block title %}
    <title>Create student</title>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

students/templates/students-edit.html
{% extends 'base.html' %}
{% block title %}
    <title>Students edit</title>
{% endblock %}
{% block links_scripts %}
{% endblock %}
{% block content %}
    {% load crispy_forms_tags %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <script>
            $(function () {
                $(".date_picker").datepicker();
            });

        </script>
        <button type="submit">EDIT</button>
        <button type="button" onclick='history.back()' value="reset">CANCEL</button>
        <input type="button" onclick="window.location.href='{% url 'students:remove' form.instance.uuid %}'"
               value="DELETE"/>
    </form>
{% endblock %}

students/templates/view-all-students.html
{% extends 'base.html' %}
{% block title %}
    <title>All sudents</title>
{% endblock %}
{% block content %}
    <p>
        <a href="{% url 'students:create' %}">Create student</a>
    </p>
    <table border="1">
        <tr>
            <td>
                <form>
                    <label for="first_name">First name: </label>
                    <input name="first_name"><br>
                    <label for="last_name">Last name: </label>
                    <input name="last_name"><br>
                    <label for="rating">Birth date: </label>
                    <input name="rating"><br>
                    <button type="submit">Search</button>
                </form>
            </td>
        </tr>
    </table>
    <p></p>
    <table border="1">
        <caption>Students</caption>
        <tr>
            <th></th>
            <th>#</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Rating</th>
            <th>Date of birth</th>
            <th>Telephone</th>
            <th>Group</th>
        </tr>
        {% for student in all_students %}
            <tr>
                <td><a href="{% url 'students:edit' student.uuid %}">EDIT</a></td>
                <td> {{ student.id }}</td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.rating }}</td>
                <td>{{ student.date_of_birth }}</td>
                <td> {{ student.phone_number }}</td>
                <td>{{ student.group.group_name }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}