groups/urls.py
from django.urls import path

from groups.views import create_group, group_edit, remove_group, view_all_groups

app_name = 'groups'

urlpatterns = [
    path('list/', view_all_groups, name='list_all'),
    path('create/', create_group, name="create"),
    path('edit/<uuid:group_id>', group_edit, name='edit'),
    path('remove/<uuid:group_id>', remove_group, name='remove')
]

lms/urls.py
from core.views import index

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', index, name="index"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

groups/models.py
import uuid as uuid

from django.db import models


class Group(models.Model):
    group_name = models.CharField(max_length=150, null=False)
    description = models.CharField(max_length=256, null=True)
    uuid = models.UUIDField(auto_created=True, editable=False, default=uuid.uuid4)
    teacher = models.ForeignKey(
        'teachers.Teacher',
        on_delete=models.SET_NULL,
        null=True,
        related_name='+',
    )

    headman = models.OneToOneField(
        to='students.Student',
        on_delete=models.SET_NULL,
        null=True,
        related_name="head_of_group"
    )

    def __str__(self):
        return f'{self.group_name}'

groups/forms.py
from django import forms

from groups.models import Group

from students.models import Student


class GroupsForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['group_name', 'description', 'teacher', 'headman']

    def __init__(self, group_uuid, *args, **kwargs):
        super(GroupsForm, self).__init__(*args, **kwargs)
        self.fields['headman'].queryset = Student.objects.filter(group__id=group_uuid)

groups/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
# Create your views here.
from django.urls import reverse

from groups.forms import GroupsForm
from groups.models import Group


def create_group(request):
    if request.method == 'GET':
        return render(
            request=request,
            context={
                "form": GroupsForm()
            },
            template_name="group-create.html"
        )
    if request.method == "POST":
        form = GroupsForm(
            data=request.POST
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list_all'))


def view_all_groups(request):
    return render(
        request=request,
        context={
            "all_groups": Group.objects.all()
        },
        template_name="view-all-group.html"
    )


def group_edit(request, group_id):
    try:
        group = Group.objects.get(uuid=group_id)
        form = GroupsForm(instance=group, group_uuid=group.id)
    except Group.DoesNotExist:
        return Http404("Student DoesNotExist")

    if request.method == "POST":
        form = GroupsForm(
            instance=group,
            data=request.POST,
            group_uuid=group.id
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("groups:list_all"))
    return render(
        request=request,
        context={
            "form": form,
            "group": group,
        },
        template_name="group-edit.html"
    )


def remove_group(request, group_id):
    group = get_object_or_404(Group, uuid=group_id)
    if request.method == 'POST':
        group.delete()
        return redirect(reverse('groups:list_all'))
    return render(
        request=request,
        context={
            "group": group,
            "what_to_delete": str(group),
        },
        template_name='group-delete.html',
    )

groups/templates/group-create.html
{% extends 'base.html' %}
{% block title %}
    <title>Create group</title>
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

groups/templates/group-delete.html
{% extends 'base.html' %}
{% block title %}
    <title>Delete group</title>
{% endblock %}
{% block content %}
   {% include "include/delete_record.html" %}
{% endblock %}

groups/templates/group-edit.html
{% extends 'base.html' %}
{% block title %}
    <title>Edit group</title>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">SUBMIT</button>
        <button type="button" onclick='history.back()' value="reset">CANCEL</button>
        <input type="button" onclick="window.location.href='{% url 'groups:remove' form.instance.uuid %}'"
               value="DELETE"/>
    </form>
{% endblock %}

groups/templates/view-all-group.html
{% extends 'base.html' %}
{% block title %}
    <title>All groups</title>
{% endblock %}
{% block content %}
    <p>
        <a href="{% url 'groups:create' %}">Create group</a>
    </p>
    <table border="1">
        <caption>Students</caption>
        <tr>
            <th>#</th>
            <th>Group name</th>
            <th>Group description</th>
            <th>Teacher</th>
            <th>headman</th>
            <th></th>
        </tr>
        {% for group in all_groups %}
            <tr>
                <td> {{ group.id }}</td>
                <td>{{ group.group_name }}</td>
                <td>{{ group.description }}</td>
                <td>
                    <table>
                        <tr>
                            <td>{{ group.teacher.first_name }}</td>
                            <td>{{ group.teacher.last_name }}</td>
                        </tr>
                    </table>
                </td>
                <td>
                    <table>
                        <tr>
                            <td>{{ group.headman.first_name }}</td>
                            <td>{{ group.headman.last_name }}</td>
                        </tr>
                    </table>
                </td>
                <td><a href="{% url 'groups:edit' group.uuid %}">EDIT</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}