groups/urls.py
from django.urls import path

from groups.views import create_group, group_edit, remove_group, view_all_groups

app_name = 'groups'

urlpatterns = [
    path('list/', view_all_groups, name='list_all'),
    path('create/', create_group, name="create"),
    path('edit/<uuid:group_id>', group_edit, name='edit'),
    path('remove/<uuid:group_id>', remove_group, name='remove')
]

lms/urls.py
from core.views import index

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', index, name="index"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

teachers/urls.py
from django.urls import path

from teachers.views import teacher_create, teacher_edit, teacher_remove, teachers_list

app_name = 'teachers'

urlpatterns = [
    path('list/', teachers_list, name='list_all'),
    path('create/', teacher_create, name='create'),
    path('edit/<uuid:teacher_uuid>', teacher_edit, name='edit'),
    path('remove/<uuid:teacher_uuid>', teacher_remove, name='remove'),
]

teachers/models.py
import datetime
import uuid

from django.db import models


# Create your models here.


class Teacher(models.Model):
    first_name = models.CharField(max_length=150, null=False)
    last_name = models.CharField(max_length=150, null=False)
    date_of_birth = models.DateField(default=datetime.datetime.now(), null=True)
    uuid = models.UUIDField(auto_created=True, editable=False, default=uuid.uuid4)

    def __str__(self):
        return f'{self.first_name}  {self.last_name}'

teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeachersForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'date_of_birth']

teachers/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from groups.models import Group

from teachers.forms import TeachersForm
from teachers.models import Teacher


def teachers_list(request):
    return render(
        context={
            'all_teachers': Teacher.objects.all(),
        },
        request=request,
        template_name='view-all-teachers.html',
    )


def teacher_create(request):
    if request.method == 'POST':
        form = TeachersForm(
            data=request.POST
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("teachers:list_all"))
    if request.method == "GET":
        return render(
            request=request,
            context={
                "form": TeachersForm(),
            },
            template_name='teacher-create.html',
        )


def teacher_edit(request, teacher_uuid):
    try:
        teacher = Teacher.objects.get(uuid=teacher_uuid)
        groups = Group.objects.all().filter(teacher__uuid=teacher.uuid)
        form = TeachersForm(instance=teacher)
    except Teacher.DoesNotExist:
        return Http404("Student DoesNotExist")

    if request.method == "POST":
        form = TeachersForm(
            instance=teacher,
            data=request.POST,
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("teachers:list_all"))

    return render(
        request=request,
        context={
            "form": form,
            "groups": groups,
        },
        template_name="teacher-edit.html"
    )


def teacher_remove(request, teacher_uuid):
    teacher = get_object_or_404(Teacher, uuid=teacher_uuid)
    if request.method == 'POST':
        teacher.delete()
        return redirect(reverse('teachers:list_all'))
    return render(
        request=request,
        context={
            "what_to_delete": str(teacher),
            "url_to_redirect": "{% url 'teachers:list_all' %}"
        },
        template_name='teacher-delete.html',
    )

teachers/templates/teacher-create.html
{% extends 'base.html' %}
{% block title %}
    <title>Create teacher</title>
{% endblock %}
{% block content %}
    <table border="1">
        <tr>
            <td>
                <form name="create_user" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button name="create" type="submit">Create</button>
                </form>
            </td>
        </tr>
    </table>
{% endblock %}

teachers/templates/teacher-delete.html
{% extends 'base.html' %}
{% block title %}
    <title>Delete teacher</title>
{% endblock %}
{% block content %}
    {% include 'include/delete_record.html'%}
{% endblock %}

teachers/templates/teacher-edit.html
{% extends 'base.html' %}
{% block title %}
    <title>Edit teacher</title>
{% endblock %}
{% block content %}
    <table border="1">
        <tr>
            <td>
                <form name="create_teacher" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button name="create" type="submit">SUBMIT</button>
                    <button type="button" onclick=onclick='history.back()' value="reset"> CANCEL</button>
                    <input type="button" onclick="window.location.href='{% url 'teachers:remove' form.instance.uuid %}'"
                           value="DELETE"/>
                </form>
            </td>
        </tr>
    </table>
    <p>
    </p>
    {% if groups|length == 0 %}
        <span>Teacher does not has groups!</span>
    {% else %}
        <table border="1">
            <caption>Groups</caption>
            <tr>
                <th>Group name</th>
            </tr>
            {% for group in groups %}
                <tr>
                    <th><a href="{% url 'groups:edit' group.uuid %}">{{ group.group_name }}</a></th>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

teachers/templates/view-all-teachers.html
{% extends 'base.html' %}
{% block title %}
    <title>All teachers</title>
{% endblock %}

{% block content %}
    <a href="{% url 'teachers:create' %}">Create teacher</a>
    <p></p>
    <table border="1">
        <caption>Teachers</caption>
        <tr>
            <th></th>
            <th>#</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Date of birth</th>
        </tr>
        {% for teacher in all_teachers %}
            <tr>
                <td><a href="{% url 'teachers:edit' teacher.uuid %}">EDIT</a></td>
                <td> {{ teacher.id }}</td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.date_of_birth }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}