groups/urls.py
from django.urls import path

from groups.views import create_group, group_edit, remove_group, view_all_groups

app_name = 'groups'

urlpatterns = [
    path('list/', view_all_groups, name='list_all'),
    path('create/', create_group, name="create"),
    path('edit/<uuid:group_id>', group_edit, name='edit'),
    path('remove/<uuid:group_id>', remove_group, name='remove')
]

lms/urls.py
from core.views import index

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', index, name="index"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import edit_student, generate_students, remove_student, students_create, view_all_students

app_name = 'students'

urlpatterns = [
    path('list/', view_all_students, name='list_all'),
    path('generate/', generate_students, name='generate'),
    path('create/', students_create, name='create'),
    path('edit/<str:student_id>', edit_student, name='edit'),
    path('remove/<str:student_id>', remove_student, name='remove')
]

teachers/urls.py
from django.urls import path

from teachers.views import teacher_create, teacher_edit, teacher_remove, teachers_list

app_name = 'teachers'

urlpatterns = [
    path('list/', teachers_list, name='list_all'),
    path('create/', teacher_create, name='create'),
    path('edit/<uuid:teacher_uuid>', teacher_edit, name='edit'),
    path('remove/<uuid:teacher_uuid>', teacher_remove, name='remove'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

</head>
<body onload="myFunc()">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">LMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active"><a href="{% url 'students:list_all' %}" class="nav-link">Students</a></li>
            <li class="nav-item"><a href="{% url 'teachers:list_all' %}" class="nav-link">Teachers</a></li>
            <li class="nav-item"><a href="{% url 'groups:list_all' %}" class="nav-link">Groups</a></li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>